name: build_JvlongGSIs

on:
  watch:
    types: [started]
    
env:
  ROM_URL: https://android.googleapis.com/packages/ota-api/vsmart_v420a_v420aopen/e3782718c6cfcc9dfd0838a7ecc97216a6ef5e25.zip
  ROM_NAME: Generic
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Clean Up
         run: |
           docker rmi `docker images -q`
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean 
       
       - name: Clone ErfanGSI Source Code
         run:  git clone https://github.com/together08/GSI-BUILD-TOOL.git --depth=1
       
       - name: Setting up JvlongGSI requirements
         run: |
             sudo chmod -R 777 GSI-BUILD-TOOL
             cd GSI-BUILD-TOOL
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: |
              wget $ROM_URL -O ./rom.zip
              sudo ./GSI-BUILD-TOOL/make.sh ./rom.zip $ROM_NAME
       
       - name: Zip GSI  
         run: |
              mkdir final
              zip -r final/GSI.zip /home/runner/work/actions_build_ErfanGSIs/actions_build_JvlongGSIs/GSI-BUILD-TOOL/output/
       
       - name: Upload GSI to WeTransfer
         run: |
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet final/GSI.zip

         
            
